export const menuLinks = [
  { label: "HOME" },
  { label: "ABOUT US" },
  { label: "EXAM" },
  {
    label: "COURSES",
    boxes: [
      [
        "Engineering Courses",
        "B.E/B.Tech",
        "M.E/M.Tech",
        "Ph.D.",
        "Diploma Courses",
      ],
      ["Medical Courses", "MBBS", "MD", "BAMS", "BDS", "MDS", "MS"],
      ["Management Courses", "BBA", "BMS", "BBM", "BHMCT", "MHM"],
      ["LAW Courses", "B.A. LL.B.", "LL.B.", "LL.M.", "B.Sc. LL.B"],
    ],
    offset: -720,
  },
  {
    label: "ENGINEERING",
    boxes: [
      [
        "Top Rank Colleges",
        "Top Engineering Colleges",
        "Top Private Engineering Colleges",
        "Top IITs in India",
        "Top NITs in India",
        "Top Colleges in Bangalore",
      ],
      [
        "College By Courses",
        "Nursing Colleges",
        "B.Optom Colleges",
        "BPT Colleges",
        "BPT Colleges",
        "All College By Courses",
      ],
      [
        "Popular Courses",
        "B.E/B.Tech",
        "M.E/M.Tech",
        "Ph.D.",
        "Diploma Courses",
        "Distance Diploma Courses",
      ],
      [
        "Popular Exams",
        "NEET Exam",
        "COMEDK",
        "UPSEE",
        "Jee Main",
        "All Engineering Exams",
      ],
    ],
    offset: -800,
  },
  {
    label: "MEDICAL",
    boxes: [
      [
        "Top Rank Colleges",
        "Top MBBS Colleges in India",
        "Top Dental Colleges in India",
        "Top Pharmacy Colleges in India",
        "Top BAMS Colleges in India",
        "Top BHMS Colleges in India",
      ],
      ["Popular Courses", "MBBS", "MD", "MS", "BAMS", "BDS"],
      [
        "Popular Exams",
        "NEET UG",
        "NEET PG",
        "AIIMS PG",
        "JIPMER PG",
        "PGIMER Exam",
      ],
      ["College By City", "Noida", "Mumbai", "Bangalore", "Chennai", "Pune"],
    ],
    offset: -900,
  },
  {
    label: "MANAGEMENT",
    boxes: [
      [
        "Top Rank Colleges",
        "IFIM Business School",
        "IIM, Ahmedabad (IIMA)",
        "Indian School Of Business (ISB)",
        "Indian Institute Of Management Bangalore (IIMB)",
        "Indian Institute Of Management, Udaipur (IIMU)",
      ],
      ["Popular Courses", "BBA", "MBA", "BMS", "BHMCT", "MHM", "EMBA"],
      [
        "Popular Exams",
        "NEET UG",
        "NEET PG",
        "AIIMS PG",
        "JIPMER PG",
        "PGIMER Exam",
      ],
      ["College By City", "Noida", "Mumbai", "Bangalore", "Chennai", "Pune"],
    ],
    offset: -1000,
  },
  { label: "LAW" },
  { label: "CONTACT US" },
];
